repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: fix-byte-order-marker
        exclude: 3rd-parties/
      - id: check-case-conflict
        exclude: 3rd-parties/
      - id: check-merge-conflict
        exclude: 3rd-parties/
      - id: check-symlinks
        exclude: 3rd-parties/
      - id: check-yaml
        exclude: kubernetes
      - id: end-of-file-fixer
        exclude: 3rd-parties/
      - id: mixed-line-ending
        exclude: 3rd-parties/
      # Prevent direct commits to the following branches
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace
        exclude: 3rd-parties/
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.3
    hooks:
      - id: clang-format
        args: [--style=Google, -i]
        exclude: 3rd-parties/
  - repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
    rev: v0.6.13
    hooks:
      - id: cmake-format
        exclude: 3rd-parties/
