name: customer

services:
  customer:
    image: customer:latest
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://dashboard:18889"
      - OTEL_SERVICE_NAME="customer"
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      dashboard:
        condition: service_started
  dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - "18888:18888"
      - "4317:18889"
      - "4318:18890"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
